const Products = [
  {
    id: "1",
    category: "green",
    name: "Bơ",
    price: 250,
    rating: 4.5,
    description:
      "Đây là quả bơ, dùng để làm sinh tố hoặc ghép vào với nhau để thành rapper",
    image: "avocado.jpeg",
  },
  {
    id: "2",
    category: "green",
    name: "Rau Rền",
    price: 100,
    rating: 5,
    description: "Đây là loại rau dễ xơi nhất",
    image: "broccoli.jpeg",
  },
  {
    id: "3",
    category: "green",
    name: "Tỏi",
    price: 250,
    rating: 2.5,
    description: "Đây là hung khí của ca sĩ Châu Việt Cường",
    image: "garlic.jpeg",
  },
  {
    id: "4",
    category: "cloth",
    name: "Dép Dọ",
    price: 250,
    rating: 5,
    description: "Sandal của các cụ ngày xưa",
    image: "depdo.jpeg",
  },
  {
    id: "5",
    category: "cloth",
    name: "Tông Lào",
    price: 250,
    rating: 4,
    description: "Kẹo cao su dành cho cún cưng",
    image: "tonglao.jpeg",
  },
  {
    id: "6",
    category: "cloth",
    name: "Quần Què",
    price: 250,
    rating: 3,
    description: "Cái quần bị què",
    image: "quanque.jpeg",
  },
  {
    id: "7",
    category: "cloth",
    name: "Áo Què",
    price: 250,
    rating: 2.5,
    description: "Cái áo bị què",
    image: "aoque.jpeg",
  },
  {
    id: "8",
    category: "dehydrated",
    name: "Bánh Mì Mốc",
    price: 500,
    rating: 1.0,
    description: "Có tặng kèm thuốc tẩy mốc",
    image: "banhmimoc.jpeg",
  },
  {
    id: "9",
    category: "dehydrated",
    name: "Bò Khô",
    price: 250,
    rating: 3.5,
    description: "Làm từ thịt heo nguyên chất 100%",
    image: "bokho.jpeg",
  },
];

export default Products;
